New Calibration Step and Sector Analysis
djgagne/hagelslag pull request #14
Opened 2019-02-27 22:08 UTC by alburke

I have added a new calibration step named "hscalibration" and updated messages for missing model output. Also, hagelslag now has the ability to work with sector data by including weights for training the ML model and outputting track data specifically within a given region.

2019-02-27 22:17 UTC, alburke commented
I realized some of the folders copied over themselves, so I will delete the old folders and resubmit a new pull request.

2019-03-09 02:40 UTC, djgagne requested changes
Can you make sure the paths in the hsdata, hsforecast, and hsplotter use /usr/bin/env python instead of your tmp path? If that isn’t working, we may need to figure out a different path option.

2019-03-09 02:40 UTC, djgagne commented on bin/hsforecast
> +#!/home/tmp/aburke/miniconda3/envs/hail/bin/python
Can you switch this back to /usr/bin/env python? Using your specific path won’t make it usable by others.

2019-03-09 02:58 UTC, alburke commented
All of the files in /bin are back to the original python path!

2019-03-09 03:30 UTC, djgagne approved these changes

2019-03-09 03:30 UTC, merged